# Generated by Django 3.2.8 on 2021-10-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_bids_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='message',
            field=models.TextField(blank=True, default='default message', null=True),
        ),
    ]
