# Generated by Django 3.2.8 on 2021-10-28 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_bids_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='bidder',
        ),
    ]
