# Generated by Django 3.2.8 on 2021-11-13 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20211113_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='message',
            field=models.ForeignKey(blank=True, default='defualt comment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='auctions.comments'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(blank=True, default='default comment', null=True),
        ),
    ]
