# Generated by Django 3.2.8 on 2021-11-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20211113_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment',
            new_name='comment_text',
        ),
        migrations.AlterField(
            model_name='bids',
            name='message',
            field=models.TextField(blank=True, default='default message', null=True),
        ),
    ]
